### ISSUE TITLE
Build of 64-bit Python 2.7 failing on AppVeyor

### ISSUE THREAD

**Issue by joachimmetz** [libyal/libyal#82]
From https://ci.appveyor.com/project/libyal/libsigscan/builds/27897464/job/48x23lin6o5oku0j

```
building 'pysigscan' extension
Traceback (most recent call last):
  File "setup.py", line 348, in <module>
    data_files=[(PYTHON_LIBRARY_DIRECTORY, LIBRARY_DATA_FILES)],
  File "C:\Python27-x64\lib\distutils\core.py", line 151, in setup
    dist.run_commands()
  File "C:\Python27-x64\lib\distutils\dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "C:\Python27-x64\lib\distutils\dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 45, in run
    bdist_msi.run(self)
  File "C:\Python27-x64\lib\distutils\command\bdist_msi.py", line 182, in run
    self.run_command('build')
  File "C:\Python27-x64\lib\distutils\cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "C:\Python27-x64\lib\distutils\dist.py", line 972, in run_command
    cmd_obj.run()
  File "C:\Python27-x64\lib\distutils\command\build.py", line 127, in run
    self.run_command(cmd_name)
  File "C:\Python27-x64\lib\distutils\cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "C:\Python27-x64\lib\distutils\dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 108, in run
    build_ext.run(self)
  File "C:\Python27-x64\lib\distutils\command\build_ext.py", line 340, in run
    self.build_extensions()
  File "setup.py", line 80, in build_extensions
    build_ext.build_extensions(self)
  File "C:\Python27-x64\lib\distutils\command\build_ext.py", line 449, in build_extensions
    self.build_extension(ext)
  File "C:\Python27-x64\lib\distutils\command\build_ext.py", line 499, in build_extension
    depends=ext.depends)
  File "C:\Python27-x64\lib\distutils\msvc9compiler.py", line 473, in compile
    self.initialize()
  File "C:\Python27-x64\lib\distutils\msvc9compiler.py", line 383, in initialize
    vc_env = query_vcvarsall(VERSION, plat_spec)
  File "C:\Python27-x64\lib\distutils\msvc9compiler.py", line 299, in query_vcvarsall
    raise ValueError(str(list(result.keys())))
ValueError: [u'path']
Command exited with code 1
```

**Comment by joachimmetz** [comment]
Changed distutils to setuptools which solved the issue:
https://github.com/libyal/libsigscan/commit/25085f82e37ada15e144485c922fd535f94bfe85#diff-2eeaed663bd0d25b7e608891384b7298L24
